# Generated by Django 5.1.6 on 2025-07-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("MODERATOR", "Modérateur"),
                    ("USER", "Utilisateur"),
                ],
                default="USER",
                max_length=20,
            ),
        ),
    ]
