# Generated by Django 5.2.3 on 2025-07-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensibilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('contenu', models.TextField()),
                ('auteur', models.DateField()),
                ('date_publication', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'Sensibilisation',
            },
        ),
    ]
