# Generated by Django 5.2.3 on 2025-07-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alerte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=100)),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("inconfortable", "Inconfortable"),
                            ("dangereux", "Dangereux"),
                            ("tres_dangereux", "Très Dangereux"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("date_alerte", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
