# Generated by Django 5.2.3 on 2025-07-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_alerte"),
    ]

    operations = [
        migrations.AddField(
            model_name="alerte",
            name="temp",
            field=models.FloatField(null=True),
        ),
    ]
