# Generated by Django 5.2.3 on 2025-07-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0003_alerte_temp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerte",
            name="date_alerte",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
